version: '3'

services:
  flask-http:
    privileged: true
    build:
      context: .
    volumes:
      - "./src:/application"
    networks:
      - lfg-net
    environment:
      - DEVELOPMENT=True
    user: ${UID:-1000}:${GID:-1000}
    working_dir: /application
    command: >
      python run.py
    ports:
      - "8000:8000"

networks:
  lfg-net:
    external: true
